allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lefthook: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAge: 2880
publishBranch: develop
versioning:
  changelog:
    storage: repository
